export const kitchenTimer = new Audio('./assets/kichen-timer.mp3')
export const forestBg = new Audio('./assets/Floresta.wav')
export const rainBg = new Audio("./assets/Chuva.wav")
export const coffeShopBg = new Audio("./assets/Cafeteria.wav")
export const fireplaceBg = new Audio("./assets/Lareira.wav")